review section
Roman-Lahoda/team-project-16 pull request #5
Opened 2021-05-14 18:20 UTC by LarisaShatil

html код на Отзывы, и прописаны часть стилей

2021-05-14 21:13 UTC, Roman-Lahoda requested changes

2021-05-14 21:13 UTC, Roman-Lahoda commented on src/sass/layouts/_reviews.scss
> +  margin-right: auto;
margin-left(right): auto; не имеет смысла без задания ширины ,так как блочный элемент по дефолту занимает 100% ширины родителя - это можно удалить
достаточно text-align: center;

2021-05-14 21:13 UTC, Roman-Lahoda commented on src/sass/layouts/_reviews.scss
> +  line-height: 2.71;
здесь очепятка 65px/36px=1.8

2021-05-14 21:13 UTC, Roman-Lahoda commented on src/sass/layouts/_reviews.scss
> +.wrapper--round-coners {
по идеи этот класс можно повесить на тег picture при этом прописав ещё display: block,тогда дополнительная обёртка div не нужна

2021-05-14 21:13 UTC, Roman-Lahoda commented on src/sass/layouts/_reviews.scss
> +  content: './src/images/icons/';
content: url(путь к файлу);

2021-05-14 21:13 UTC, Roman-Lahoda commented on src/sass/layouts/_reviews.scss
> +  line-height: 2.64;
не совсем понял откуда было взято значение line-height

2021-05-14 21:13 UTC, Roman-Lahoda commented on src/sass/layouts/_reviews.scss
> +  line-height: 20px;
![image](https://user-images.githubusercontent.com/79223492/118332123-4107c880-b512-11eb-876a-07ac227bd6f7.png)

2021-05-15 04:28 UTC, LarisaShatil commented on src/sass/layouts/_reviews.scss
> +  line-height: 2.71;
все правильно, как в макете - Mobile First) это в десктопе будет 1.8

2021-05-15 04:30 UTC, LarisaShatil commented on src/sass/layouts/_reviews.scss
> +  margin-right: auto;
хорошо, согласна

2021-05-15 04:37 UTC, LarisaShatil commented on src/sass/layouts/_reviews.scss
> +.wrapper--round-coners {
да, супер! сработало

2021-05-15 09:05 UTC, Roman-Lahoda commented on src/sass/layouts/_reviews.scss
> +  line-height: 2.71;
извини, это я туплю(

2021-05-15 10:13 UTC, LarisaShatil commented on src/sass/layouts/_reviews.scss
> +  line-height: 2.71;
все норм) рабочие моменты п.с. все мы тупим, по очереди)))

2021-05-15 11:46 UTC, Roman-Lahoda approved these changes

2021-05-15 11:46 UTC, merged